### ISSUE TITLE
Program not starting

### ISSUE THREAD

**Issue by sorentorp** [robaleman/discord-cryptocurrency-bot#2]
Hi

I stumbled upon your program, and it sounds promising!

But when I put in all the info needed, api keys for discord+binance, chan id and install all dependencies the console just makes a line-break, and nothing more happens.

` /discord-cryptocurrency-bot$ node bot.js `

I use the following command to install dependencies

`npm install discord.io fs node-binance-api node-schedule r-script-with-bug-fixes --save`

```
boyd@server:~/build/discord-cryptocurrency-bot$ node --version
v8.9.4
boyd@server:~/build/discord-cryptocurrency-bot$ npm --version
5.6.0
```

**Comment by sorentorp** [comment]
after a long while I get this error

> Running scheduled Ichimoku analysis..
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn Rscript ENOENT
>     at _errnoException (util.js:1022:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
>     at onErrorNT (internal/child_process.js:372:16)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by robaleman** [comment]
Hey sorentorp! Thanks for the issue report.

I have been having this odd problem where everytime I `npm install` any of the other packages, it will remove the discord.io package. I will try to fix it in my future, but in the meantime, doing this has worked for me:

First `npm install node-binance-api node-schedule r-script-with-bug-fixes`.

Then, as a second command, `npm install discord.io`. 

That seems to temporarily fix the problem for me, hopefully it will work for you as well.

Secondly, I also haven't updated the package.json but the node-binance-api needs to be version 4.0.3. Make sure you update that in the package.json as the current code won't work if node-binance-api is not v4.0 or higher. I'll update it in the repo now.

Let me know if that works for you - if not, happy to do some more troubleshooting.

**Comment by sorentorp** [comment]
Thank you for the response, but no luck. 

> node bot.js
> Running scheduled Ichimoku analysis..
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn Rscript ENOENT
>     at _errnoException (util.js:1022:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
>     at onErrorNT (internal/child_process.js:372:16)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by robaleman** [comment]
The fix I posted worked for me locally on a fresh installation of the repo, but I forgot to add that I'm on Linux. StackExchange seems to imply that the 'ENOENT' error is pretty common on Windows systems. Are you running Windows by chance? 

For reference, on start-up, the bot is supposed to print this to the console as soon as it connects to Discord:
```
~/discord-cryptocurrency-bot-master $ node bot.js
Connected
Logged in as: cryptocurrency-bot-401497561917161473

```

**Comment by sorentorp** [comment]
I'm on Linux (Debian).

I have just tried with a fresh git pull, install node modules, edit auth.js and config.js. 

Same result 

> node bot.js
> Running scheduled Ichimoku analysis..
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn Rscript ENOENT
>     at _errnoException (util.js:1022:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
>     at onErrorNT (internal/child_process.js:372:16)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by robaleman** [comment]
Sorry but I'm pretty stumped on this issue. Similar errors on the web point to issues with Node installations, pathing, or port settings... but I'm still ironing out bugs at this stage so this could very well also be an issue on my end. I'll definitely keep you updated if I find out anything new.

I will also be deploying this bot to Heroku very soon after a couple more version updates if you would just like to use that.

**Comment by sorentorp** [comment]
That is wierd! I will keep following your progress, and see if It gets adressed.

Heroku has no interest, for me anyway. I have a server, that I already paid for.

**Comment by droidmanspace** [comment]
Please check where R is properly installed on your system and check whether it is added to the path in System Variables.

**Comment by sorentorp** [comment]
Any progress? Even with a "clean" install, it doesn't become more responsive. 

Is there any way I can debug it for you?

**Comment by robaleman** [comment]
Haven't made any major changes to the code yet, may be busy for a few days but will resume progress soon.

And yes, definitely! Made it public so you can clone and make whatever changes to the code you want. I would maybe look at the R-Script module as that's what caused me the most trouble at first.

**Comment by sorentorp** [comment]
Okay, Great!

I'm not that much of a coder, but can I run the program in some sort of
debug mode, that gives you the information you need?
tir. 23. jan. 2018 kl. 05.36 skrev rob <notifications@github.com>:
